title: "[RFC] "
labels: ["rfc"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ideas & RFCs

        Propose new features, integrations, or structural changes to the framework.
        RFCs are the starting point for significant changes before they become issues or PRs.

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "One-paragraph overview of what you're proposing."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this needed? What use case does it serve?"
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: "Detailed Design"
      description: "How would this work? Include file structures, examples, or diagrams."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "What other approaches were considered?"
    validations:
      required: false
