title: "[Roadmap] "
labels: ["roadmap"]
body:
  - type: markdown
    attributes:
      value: |
        ## Roadmap Discussion

        Use this template to discuss known limitations, propose solutions, and share research
        on how to evolve the Agentic Enterprise framework.

        See the [Known Limitations](https://github.com/wlfghdr/agentic-enterprise#known-limitations--roadmap)
        section in the README for the full list.

  - type: dropdown
    id: limitation
    attributes:
      label: "Related Limitation"
      description: "Which known limitation does this relate to?"
      options:
        - "#1 — Mono-repo simplification"
        - "#2 — No agent runtime included"
        - "#3 — Quality policies are stubs"
        - "#4 — Governance not wired"
        - "#5 — AGENT.md only — no skills/tools/MCP"
        - "#6 — PR-only interaction"
        - "#7 — No dashboards or visualization"
        - "#8 — No cross-repo orchestration"
        - "#9 — Agent instructions not enforced"
        - "#10 — No real system connections"
        - "New limitation / not listed"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context & Research"
      description: "Share what you've found — tools, patterns, prior art, or implementation ideas."
      placeholder: |
        Include links to relevant projects, docs, or examples.
        The more concrete, the better!
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Approach"
      description: "How would you solve this? What trade-offs exist?"
    validations:
      required: false
