name: "🏗️ Framework Improvement"
description: "Propose changes to the operating model — layers, loops, agent hierarchy, or policies"
title: "[Framework] "
labels: ["framework", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the Agentic Enterprise framework!
        Please fill out the sections below so the community can evaluate your proposal.

  - type: dropdown
    id: area
    attributes:
      label: "Affected Area"
      description: "Which part of the framework does this change affect?"
      options:
        - "Layer 0 — Steering"
        - "Layer 1 — Strategy"
        - "Layer 2 — Orchestration"
        - "Layer 3 — Execution"
        - "Layer 4 — Quality"
        - "Loop 1 — Discover & Decide"
        - "Loop 2 — Design & Build"
        - "Loop 3 — Validate & Ship"
        - "Loop 4 — Operate & Evolve"
        - "Agent instruction hierarchy"
        - "Templates"
        - "CONFIG.yaml structure"
        - "Cross-cutting / multiple areas"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem or Gap"
      description: "What's missing, broken, or could be better?"
      placeholder: "Describe the current limitation or gap in the framework..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Change"
      description: "How would you improve it? Be specific about files, structure, or content."
      placeholder: |
        - Which files would change?
        - What would the new content look like?
        - How does it maintain consistency with the rest of the model?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "What other approaches did you consider?"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission checklist"
      options:
        - label: "I've read [CONTRIBUTING.md](../CONTRIBUTING.md)"
          required: true
        - label: "This change doesn't break the layer separation principle"
          required: true
        - label: "This is a framework improvement (not a fork customization)"
          required: true
