name: "📜 Quality Policy Improvement"
description: "Improve or add quality policies (security, architecture, performance, etc.)"
title: "[Policy] "
labels: ["policy", "quality"]
body:
  - type: dropdown
    id: domain
    attributes:
      label: "Policy Domain"
      options:
        - "architecture"
        - "content"
        - "customer"
        - "delivery"
        - "experience"
        - "observability"
        - "performance"
        - "security"
        - "New domain (describe below)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "What needs to change?"
      description: "Describe the policy gap or improvement. Reference industry standards where applicable (OWASP, CIS, NIST, SLSA, etc.)."
    validations:
      required: true

  - type: textarea
    id: policy-content
    attributes:
      label: "Proposed Policy Content"
      description: "Draft the policy rules. Policies must be actionable and machine-auditable — agents need to evaluate compliance."
      render: markdown
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "Industry Standard References"
      description: "Link to relevant standards, benchmarks, or frameworks."
      placeholder: |
        - OWASP ASVS: https://github.com/OWASP/ASVS
        - CIS Benchmarks: https://www.cisecurity.org/cis-benchmarks
        - NIST CSF: https://www.nist.gov/cyberframework
    validations:
      required: false
